/** @format */

import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReactQueryProvider } from '@/lib/ReactQueryProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { AppProvider, useApp } from '@/context/AppContext';
import Sidebar from '@/components/sidebar/Sidebar';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ReactQueryProvider>
					<AppProvider>
						<div className='flex'>
							<Sidebar />
							{children}
						</div>
						<ReactQueryDevtools initialIsOpen={false} />
					</AppProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
